### ISSUE TITLE
feature: list of open source repos

### ISSUE THREAD

**Issue by sayanee** [webuildsg/iOS#1]
@subhransu, any chance of [adding in the feature](https://github.com/webuildsg/iOS/blob/master/README.md#feature-list) to list **open source repos**? :smiley: Here's the [api endpoint to query for repos](https://webuild.sg/api/v1/repos).

Great work so far! So exciting to see `swift` code for watch too :tada:

**Comment by subhransu** [comment]
@sayanee I thought about it. But just by showing the repos on a mobile device might not make more sense. Because, users won't be able to do much with it. 

Any thoughts around that?

**Comment by notthetup** [comment]
A link to Github would be interesting. Is there a Github app on IOS now a days? If they publish a URL scheme you could be able to hook into that.

**Comment by subhransu** [comment]
@notthetup no official GitHub iOS app yet. So I think will just redirect them to the repo and probably couple of steps to clone the repo (for first timers)

**Comment by sayanee** [comment]
for now, just a simple link to the url and it can be opened on the browser?

**Comment by subhransu** [comment]
Alright will add that.
