### ISSUE TITLE
Add event to calendars 

### ISSUE THREAD

**Issue by subhransu** [webuildsg/iOS#10]
It will be really good to add events to calendar. Tricky part is though if user adds an event to calendar what happens to RSVP.

Never the less we should have this feature. You can use **EventKit** for this
- [Apple Documentation](https://developer.apple.com/library/ios/documentation/DataManagement/Conceptual/EventKitProgGuide/Introduction/Introduction.html)
- [RayWenderlich Tutorial](http://www.raywenderlich.com/64513/cookbook-making-calendar-reminder) -- although this is more about reminders

**Comment by sayanee** [comment]
thank you so much @subhransu - agreed this is much needed!

**Comment by sayanee** [comment]
- reference example: https://stackoverflow.com/questions/28379603/how-to-add-an-event-in-the-device-calendar-using-swift
- reference video: https://www.youtube.com/watch?v=KgrY-UJTPRY

**Comment by sayanee** [comment]
fugly button - amend the button:

<img width="578" alt="screenshot 2016-04-26 23 05 43" src="https://cloud.githubusercontent.com/assets/413879/14823015/7dea931c-0c03-11e6-9c96-be5de1aa11e6.png">

Confirmation alert look:

<img width="578" alt="screenshot 2016-04-26 23 05 52" src="https://cloud.githubusercontent.com/assets/413879/14823026/88be710a-0c03-11e6-9363-0b155fbc1f4b.png">

**Comment by sayanee** [comment]
proposed button layout:

<img width="578" alt="screenshot_2016-04-26_23_05_43" src="https://cloud.githubusercontent.com/assets/413879/14823166/12edba98-0c04-11e6-997f-3a9e06b6e697.png">

**Comment by sayanee** [comment]
buttons aligned:

<img width="578" alt="screenshot 2016-04-27 10 28 59" src="https://cloud.githubusercontent.com/assets/413879/14840075/32bbc068-0c63-11e6-96c6-7a24e917f864.png">
