### ISSUE TITLE
Text truncation on details page

### ISSUE THREAD

**Issue by subhransu** [webuildsg/iOS#11]
Probably need to increase the height of the label or set the auto-layout to adjust the height of the text. 
### Current screenshot with truncation

![webuild_sg](https://cloud.githubusercontent.com/assets/1495621/13561456/36bc9bec-e468-11e5-84c9-0c677903695d.PNG)

**Comment by sayanee** [comment]
:+1: :100: 

Will be changing this entire view to a `TableViewController` with each cell as one info #1 So that should fix it :smiley:

**Comment by sayanee** [comment]
related to #1
