### ISSUE TITLE
Crash log from Apple review

### ISSUE THREAD

**Issue by sayanee** [webuildsg/iOS#15]
❗ ❗ [Analyzing Crash Reports](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AnalyzingCrashReports/AnalyzingCrashReports.html)

![image](https://cloud.githubusercontent.com/assets/413879/14857450/e81d2562-0cce-11e6-8b2a-376eb654ac14.png)

**Comment by cheeaun** [comment]
😱

**Comment by cheeaun** [comment]
Probably @lxcid can help?

**Comment by lxcid** [comment]
Ahhh. Do you have the symbolicated crash log? A screenshot of it?

*\* I'm heading to bed soon. I'll check back tomorrow morning! Sorry about that! **

**Comment by lxcid** [comment]
Some possible steps to take:
- http://stackoverflow.com/a/28577267
- http://stackoverflow.com/a/28474261

**Comment by notthetup** [comment]
I think the issue is fixed (it was a swift optional type casting issue). But just need to double check if the crash seen by apple is the same as the one we saw.

**Comment by sayanee** [comment]
Trying to download the crash log sent by Apple and trying to figure out how to use it in xCode. Will keep everyone updated! Thanks all 😍

![screenshot 2016-04-28 09 34 13](https://cloud.githubusercontent.com/assets/413879/14873009/67901048-0d24-11e6-953d-6fc0d693b649.png)
