### ISSUE TITLE
publish to app store

### ISSUE THREAD

**Issue by sayanee** [webuildsg/iOS#5]
1. [x] enrol in apple developer program
2. [x] get approval for apple developer program
3. [x] upload app for approval
4. [x] app "Waiting for Review"
5. [x] get app on the app store

**Comment by jurvis** [comment]
looks good!!!

**Comment by sayanee** [comment]
thank you @jurvis still have a few to [refactor](https://github.com/webuildsg/iOS/issues?q=is%3Aissue+is%3Aopen+label%3Arefactor) and [enhance](https://github.com/webuildsg/iOS/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) a little!  #learning :heart_eyes:

**Comment by sayanee** [comment]
_Warning_: Upload to App Store - [possible reason](http://stackoverflow.com/a/27467839/496797)

![image](https://cloud.githubusercontent.com/assets/413879/13452950/950c42fe-e087-11e5-93eb-a8f1d7a22e11.png)

![image](https://cloud.githubusercontent.com/assets/413879/13454346/74227310-e091-11e5-9322-8b335a0805dd.png)

**Comment by jurvis** [comment]
@sayanee been getting that problem every now and then - nothing to be worried about 👍🏻

**Comment by sayanee** [comment]
_phew_ 😅 i mean of course every other app will use some kind of API right? :laughing:

**Comment by sayanee** [comment]
To fix all pending issues:

> We are writing to let you know the results of your appeal for your app, We Build SG.
> 
> The App Review Board evaluated your app and determined that the original rejection feedback is valid. Your app does not comply with:
> 
> 10.6: Apple and our customers place a high value on simple, refined, creative, well thought through interfaces. They take more work but are worth it. Apple sets a high bar. If your user interface is complex or less than very good it may be rejected
> 
> Therefore, your app will not be posted to the App Store at this time.
> 
> Thank you for providing more detail about how you built the app. However, there are some aspects of your app that should be improved:
> - your app appears like an HTML app or a web site: It does not include navigation elements other than a back button. It has no tab bar, no menu bar
> - your app does not have any visual UI elements that identify it as an iOS app
> - your app links out to Safari for most of the information that is listed. It appears to be simply an aggregator of web content. 
> 
> We hope you will consider making the necessary changes to be in compliance with the App Store Review Guidelines and will resubmit your revised binary.

**Comment by cheeaun** [comment]
😅

**Comment by notthetup** [comment]
Translation: STAPH MAKING WEB APPS INTO NATIVE APPS!! :stuck_out_tongue:

**Comment by sayanee** [comment]
ok fine  @notthetup 😆Hey! The issues on #3 and #4 will be using native functions 😝 Back to coding then!

**Comment by sayanee** [comment]
Let's see...

![image](https://cloud.githubusercontent.com/assets/413879/14917702/e7016c6c-0e52-11e6-89ed-1d1bf81f763d.png)

**Comment by sayanee** [comment]
Download NOW: https://itunes.apple.com/us/app/we-build-sg/id1089421487?mt=8

![13047927_10156827115365557_3921807380795907885_o](https://cloud.githubusercontent.com/assets/413879/14932329/139d2834-0ea7-11e6-89c7-15758e388a2f.jpg)
