### ISSUE TITLE
open register event link from within app itself without deeplinking

### ISSUE THREAD

**Issue by jurvis** [webuildsg/iOS#6]
currently you're taken out of the WeBuild app to Safari in order to browse the event registration page, will it be better to use `SFSafariViewController` to present from within your app instead so the user can easily get back to where they're at?

**Comment by sayanee** [comment]
So I think, from iOS 9 this new feature is available - the native back button to another app. :sob: Can't find the docs. But it looks like this. Hence I did not bother to open it within the app. What do you think?

![2016-02-14_21_34_58](https://cloud.githubusercontent.com/assets/413879/13033966/0037ef74-d363-11e5-8b7a-bbbf146c8ad7.jpg)

**Comment by jurvis** [comment]
yup, that certainly works, but I think it might result in users forgetting they were browsing your app after awhile.

the main advantages of this is being able to:
1. Retain the user's browsing context whilst using your app
2. Implementing Force Touch

<img width="435 alt="screenshot"  src="http://i.giphy.com/26FPy35kppc7Xu0j6.gif">

if that's something you want to implement, this guide looks good: http://code.tutsplus.com/tutorials/ios-9-getting-started-with-sfsafariviewcontroller--cms-24260

**Comment by sayanee** [comment]
good point :clap:  Will code it out in the future iterations. UX is so important :100:

**Comment by sayanee** [comment]
to read: http://code.tutsplus.com/tutorials/ios-9-getting-started-with-sfsafariviewcontroller--cms-24260
