### ISSUE TITLE
Content within Event Detail's View Controller should scroll

### ISSUE THREAD

**Issue by jurvis** [webuildsg/iOS#7]
UIScrollView all the things! :smile:

**Comment by sayanee** [comment]
Yeah, hence i'm gonna change it to #1 so that `UITableView` will come with scroll easily. Is that cooler? :sunglasses: :stuck_out_tongue_closed_eyes:

**Comment by jurvis** [comment]
right, that works fine! apologies for not spotting that issue beforehand

**Comment by sayanee** [comment]
thank you for taking time to look into this :+1:
