### ISSUE TITLE
add a loader while it fetches info when opening the app for the first time

### ISSUE THREAD

**Issue by sayanee** [webuildsg/iOS#9]
![photo 3-3-16 3 19 51 pm](https://cloud.githubusercontent.com/assets/413879/13487284/979dd5ec-e153-11e5-8164-bad15f206478.png)

**Comment by cheeaun** [comment]
:+1:

**Comment by sayanee** [comment]
Added `Activity Indicator View`:

<img width="578" alt="screenshot 2016-04-26 21 35 53" src="https://cloud.githubusercontent.com/assets/413879/14820035/5399e07e-0bf7-11e6-8091-c50cd7db9815.png">
